title: zeacer
description: "Hey! I'm Zeacer, a security researcher, breaker of things, jack of all trades and master of none."
baseurl: "/"
author:
  name: "zeacer"
  email: "hello@zeacer.me"
  url: "https://zeacer.me"
  x: "https://x.com/zeac3r"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "zeacer"
year : "2025"

markdown: kramdown
kramdown:
  parse_block_html: true
